---
- name: Install Python Minimal
  gather_facts: true
  hosts: node1
  tasks:
    - name: Install Python
      raw: sudo apt update -y && sudo apt install python-minimal -y

- name: Provision Build & Deploy Step
  become: True
  hosts: node1
  tasks:
    - include_role:
        name: provision.apache
    - include_role:
        name: provision.docker
    - include_role:
        name: build.deploy
  tags:
  - provision
  - build
  - deploy 
