---
- name: Install Docker Requirements
  become: True
  apt:
    update_cache: yes
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      
- name: Add Docker GPG apt Key
  become: True
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: True
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce
  become: True
  apt: 
    name: docker-ce
    update_cache: yes 
    state: latest