---
- name: Install Docker Requirements
  become: True
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

- name: Add Docker GPG apt Key
  become: True
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  become: True
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Update apt and install docker-ce
  become: True
  apt: 
    name: docker_ce
    update_cache: yes 
    state: latest    
